# Generated by Django 3.0.7 on 2020-06-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço unitário de venda conforme negociação e configurações do sistema', max_digits=16, max_length=16, verbose_name='Preço Unitário'),
        ),
    ]
