# Generated by Django 3.0.7 on 2020-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200613_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='aberta',
            field=models.BooleanField(default=True, help_text='A mesa tem que estar aberta para constar no Pedido'),
        ),
    ]
