# Generated by Django 3.0.7 on 2020-06-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_serve_refeicao'),
        ('pedidos', '0003_mesa_aberta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
        ),
        migrations.AlterIndexTogether(
            name='pedido',
            index_together=set(),
        ),
    ]
