# Generated by Django 3.0.7 on 2020-06-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200613_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['numero']},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.ForeignKey(default='Pedido', help_text='status do pedido Orçamento/Devolução/Cancelado/Em análise crédito/Bloqueado/Faturado/quitado/Pré-Pedido etc ', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='pedidos.PedidoStatus'),
        ),
    ]
