# Generated by Django 3.0.7 on 2020-06-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20200613_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidostatus',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.ForeignKey(default='Pedido', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='pedidos.PedidoStatus'),
        ),
    ]
