# Generated by Django 2.2.10 on 2020-05-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(default='Rua do Sobe e Desce', max_length=50)),
                ('numero', models.CharField(blank=True, default='S/N', max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, default='Pituba', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, default='Salvador', max_length=50, null=True)),
                ('uf', models.CharField(default='BA', max_length=2)),
                ('telefone', models.CharField(blank=True, default='(71) 9 9999-9999', max_length=50, null=True)),
                ('cep', models.CharField(blank=True, default='41000-000', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Cadastro de Loja',
                'verbose_name_plural': 'Cadastro de Lojas',
            },
        ),
    ]
