# Generated by Django 3.0.7 on 2020-06-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(default='Rua do Sobe e Desce', max_length=50)),
                ('numero', models.CharField(blank=True, default='S/N', max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, default='Pituba', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, default='Salvador', max_length=50, null=True)),
                ('uf', models.CharField(default='BA', max_length=2)),
                ('telefone', models.CharField(blank=True, default='(71) 9 9999-9999', max_length=50, null=True)),
                ('cep', models.CharField(blank=True, default='41000-000', max_length=10, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
    ]
