# Generated by Django 3.0.7 on 2020-06-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20200611_1113'),
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AddField(
            model_name='loja',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
            preserve_default=False,
        ),
    ]
