# Generated by Django 3.0.7 on 2020-06-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20200623_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='quantidade_clientes',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd Clientes'),
        ),
    ]
