# Generated by Django 3.0.7 on 2020-06-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionarios', '0003_auto_20200625_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadastrado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
