# Generated by Django 3.0.6 on 2020-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/servicos'),
        ),
    ]
