# Generated by Django 3.0.6 on 2020-06-01 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_portifolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portifolio',
            name='foto',
            field=models.ImageField(blank=True, default='portfolio/portfolio.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='nome_projeto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portifolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
