# Generated by Django 3.0.7 on 2020-06-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('clientes', '0002_auto_20200609_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsavel', to='funcionarios.Funcionario'),
        ),
    ]
