# Generated by Django 3.0.7 on 2020-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fisica_juridica',
            field=models.CharField(choices=[('Física', 'Fisica'), ('Jurídica', 'Juridica')], default='Juridica', max_length=8, verbose_name='Tipo de Cliente'),
        ),
    ]
