# Generated by Django 3.0.7 on 2020-06-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20200609_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razao_social'], 'verbose_name': 'Cadastro de Cliente', 'verbose_name_plural': 'Cadastro de Clientes'},
        ),
    ]
