# Generated by Django 3.0.7 on 2020-06-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20200609_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True),
        ),
    ]
