# Generated by Django 3.0.7 on 2020-06-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='DIN', max_length=3, unique=True, verbose_name='Código Forma Pagamento')),
                ('descricao', models.CharField(default=' ', help_text='Descrição Forma Pagamento para venda ou compra de produtos', max_length=60, verbose_name='Descrição Forma Pagamento')),
                ('habilitado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para bloquear esta forma de pagamento nas vendas', max_length=60, verbose_name='Tipo habilitado')),
                ('negociada', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para permitir que vendedor possa negociar a forma de pagamento com cliente N- Não negocia', max_length=60, verbose_name='Pode haver negociação')),
                ('venda_parcelada', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para permitir que vendedor possa parcelar venda N- Não parcela', max_length=60, verbose_name='Pode haver parcelamento')),
                ('imprime_na_nfe', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para permitir que sistema imprima os dados financeiros na nfe / Danfe', max_length=60, verbose_name='Imprimir dados na nota fiscal')),
                ('habilitado_web', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='N', help_text='S Habilita forma de pagamento na vendas via site WEB', max_length=60, verbose_name='Habilita forma de pagamento na WEB')),
                ('num_parcelas', models.PositiveIntegerField(help_text='Numero máximo de parcelas pre determinado para este pagamento. Se zeros, força que seja a vista', verbose_name='Numero de parcelas')),
                ('prazos_padroes', models.CharField(default='000', help_text='Informe os prazos padroes em numero de dias consecutivos de 3 em 3 ex 000030060090', max_length=60, verbose_name='Prazos padroes em dias')),
                ('prazo_maximo', models.PositiveIntegerField(help_text='Número máximo de prazo em dias pre determinado para este pagamento', verbose_name='Prazo máximo em dias')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mínimo para este tipo de pagamento reverse', max_digits=16, max_length=16, verbose_name='Valor mínimo para venda')),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor máximo para este tipo de pagamento reverse', max_digits=16, max_length=16, verbose_name='Valor máximo para venda')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Pagamento',
                'verbose_name_plural': 'Tipos de Pagamentos',
                'ordering': ('descricao',),
            },
        ),
        migrations.CreateModel(
            name='PrazoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('descricao', models.CharField(max_length=60)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'Prazo de Pagamento',
                'verbose_name_plural': 'Prazos de Pagamentos',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preço',
                'ordering': ['descricao'],
                'unique_together': {('descricao', 'empresa')},
            },
        ),
    ]
