# Generated by Django 3.0.7 on 2020-06-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20200611_1113'),
        ('financeiro', '0002_tabelapreco'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazopagamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipopagamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipopagamento',
            name='habilitado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para bloquear esta forma de pagamento nas vendas', max_length=60, verbose_name='Tipo habilitado'),
        ),
        migrations.AlterField(
            model_name='tipopagamento',
            name='habilitado_web',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='N', help_text='S Habilita forma de pagamento na vendas via site WEB', max_length=60, verbose_name='Habilita forma de pagamento na WEB'),
        ),
        migrations.AlterField(
            model_name='tipopagamento',
            name='imprime_na_nfe',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para permitir que sistema imprima os dados financeiros na nfe / Danfe', max_length=60, verbose_name='Imprimir dados na nota fiscal'),
        ),
        migrations.AlterField(
            model_name='tipopagamento',
            name='negociada',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para permitir que vendedor possa negociar a forma de pagamento com cliente N- Não negocia', max_length=60, verbose_name='Pode haver negociação'),
        ),
        migrations.AlterField(
            model_name='tipopagamento',
            name='venda_parcelada',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='S', help_text='S para permitir que vendedor possa parcelar venda N- Não parcela', max_length=60, verbose_name='Pode haver parcelamento'),
        ),
    ]
