# Generated by Django 3.0.7 on 2020-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200611_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='product.jpg', upload_to='produtos'),
        ),
    ]
