# Generated by Django 3.0.7 on 2020-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20200612_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='produtos/product.jpg', upload_to='produtos'),
        ),
    ]
