# Generated by Django 3.0.7 on 2020-06-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razao_para_inativar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
