# Generated by Django 3.0.7 on 2020-06-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20200611_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='serve_refeicao',
            field=models.BooleanField(default=False),
        ),
    ]
