# Generated by Django 3.0.6 on 2020-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20200509_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logotipo',
            field=models.ImageField(blank=True, upload_to='empresas'),
        ),
    ]
