# Generated by Django 3.0.7 on 2020-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20200627_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
