# Generated by Django 3.0.7 on 2020-06-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(db_index=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=7)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('data_movimento', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CaixaMovimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_movimento', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('entrada_saida', models.CharField(choices=[('D', 'Entrada'), ('C', 'Saída')], default='D', max_length=1)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='caixas.Caixa')),
                ('tipopagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.TipoPagamento')),
            ],
        ),
    ]
